---
name: run-validator
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  run-accounts-validator:
    name: Run Accounts Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Commit status Success
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUBTOKEN }}
          script: |
            github.rest.repos.createCommitStatus({
               state: 'success',
               sha: ${{ github.sha }},
               owner: 'nikhillingaepam',
               repo: 'testrepo'
            })
     
