---
name: run-validator
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  run-accounts-validator:
    name: Run Accounts Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Commit status Success
        if: ${{ always() && (steps.validation.outcome == 'success') }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUBTOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.BODY
            })
     
